#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l vmem=16gb
#PBS -l walltime=10:00:00

export SINGULARITYENV_OMP_NUM_THREADS=7

set -e
set -x

mkdir -p output
chmod -R +w output

time singularity exec -e docker://brainlife/dipy:1.1.1 dipy_mask \
    --force \
    --out_dir output \
    --out_mask mask.nii.gz \
    --ub $(jq -r .ub config.json) \
    $(jq -r .img config.json) $(jq -r .lb config.json)

echo "done"
